export default[
    {id: '0', imagenName: 'mueble1_1.gif', tag: 'mueble 1'},
    {id: '1', imagenName: 'mueble1_1.jpg', tag: 'mueble 1'},
    {id: '2', imagenName: 'mueble1_2.jpg', tag: 'mueble 1'},
    {id: '3', imagenName: 'mueble1_3.jpg', tag: 'mueble 1'},
    {id: '4', imagenName: 'mueble1_4.jpg', tag: 'mueble 1'},
    {id: '5', imagenName: 'mueble1_5.jpg', tag: 'mueble 1'},
    {id: '6', imagenName: 'mueble1_6.jpg', tag: 'mueble 1'},
    {id: '7', imagenName: 'mueble1_7.jpg', tag: 'mueble 1'},
    {id: '8', imagenName: 'mueble1_8.jpg', tag: 'mueble 1'},
    {id: '9', imagenName: 'mueble1_9.jpg', tag: 'mueble 1'},
    {id: '10', imagenName: 'mueble1_10.jpg', tag: 'mueble 1'},
    {id: '11', imagenName: 'mueble1_11.jpg', tag: 'mueble 1'},
    {id: '12', imagenName: 'mueble1_12.jpg', tag: 'mueble 1'},
    {id: '13', imagenName: 'mueble1_13.jpg', tag: 'mueble 1'},
    {id: '14', imagenName: 'mueble1_14.jpg', tag: 'mueble 1'},
    {id: '15', imagenName: 'mueble1_15.jpg', tag: 'mueble 1'},
    {id: '16', imagenName: 'mueble1_16.jpg', tag: 'mueble 1'},
    {id: '17', imagenName: 'mueble1_17.jpg', tag: 'mueble 1'},
    {id: '18', imagenName: 'mueble1_18.jpg', tag: 'mueble 1'},
    {id: '19', imagenName: 'mueble1_19.jpg', tag: 'mueble 1'},
    {id: '20', imagenName: 'mueble1_20.jpg', tag: 'mueble 1'},

    {id: '21', imagenName: 'mueble2_1.gif', tag: 'mueble 2'},
    {id: '22', imagenName: 'mueble2_1.png', tag: 'mueble 2'},
    {id: '23', imagenName: 'mueble2_2.png', tag: 'mueble 2'},
    {id: '24', imagenName: 'mueble2_3.jpg', tag: 'mueble 2'},
    {id: '25', imagenName: 'mueble2_4.jpg', tag: 'mueble 2'},
    {id: '26', imagenName: 'mueble2_5.jpg', tag: 'mueble 2'},
    {id: '27', imagenName: 'mueble2_6.jpg', tag: 'mueble 2'},
    {id: '28', imagenName: 'mueble2_7.jpg', tag: 'mueble 2'},
    {id: '29', imagenName: 'mueble2_8.jpg', tag: 'mueble 2'},
    {id: '30', imagenName: 'mueble2_9.jpg', tag: 'mueble 2'},
    {id: '31', imagenName: 'mueble2_10.jpg', tag: 'mueble 2'},
    {id: '32', imagenName: 'mueble2_11.jpg', tag: 'mueble 2'},
    {id: '33', imagenName: 'mueble2_12.jpg', tag: 'mueble 2'},

    {id: '34', imagenName: 'mueble3_1.gif', tag: 'mueble 3'},
    {id: '35', imagenName: 'mueble3_1.png', tag: 'mueble 3'},
    {id: '36', imagenName: 'mueble3_2.png', tag: 'mueble 3'},
    {id: '37', imagenName: 'mueble3_3.jpg', tag: 'mueble 3'},
    {id: '38', imagenName: 'mueble3_4.jpg', tag: 'mueble 3'},
    {id: '39', imagenName: 'mueble3_5.jpg', tag: 'mueble 3'},
    {id: '40', imagenName: 'mueble3_6.jpg', tag: 'mueble 3'},
    {id: '41', imagenName: 'mueble3_7.jpg', tag: 'mueble 3'},
    {id: '42', imagenName: 'mueble3_8.jpg', tag: 'mueble 3'},

    {id: '43', imagenName: 'mueble4_1.gif', tag: 'mueble 4'},
    {id: '44', imagenName: 'mueble4_1.png', tag: 'mueble 4'},
    {id: '45', imagenName: 'mueble4_2.png', tag: 'mueble 4'},
    {id: '46', imagenName: 'mueble4_3.jpg', tag: 'mueble 4'},
    {id: '47', imagenName: 'mueble4_4.jpg', tag: 'mueble 4'},
    {id: '48', imagenName: 'mueble4_5.jpg', tag: 'mueble 4'},
    {id: '49', imagenName: 'mueble4_6.jpg', tag: 'mueble 4'},
    {id: '50', imagenName: 'mueble4_7.jpg', tag: 'mueble 4'},
    {id: '51', imagenName: 'mueble4_8.jpg', tag: 'mueble 4'},
    {id: '52', imagenName: 'mueble4_9.jpg', tag: 'mueble 4'},

    {id: '53', imagenName: 'mueble5_1.gif', tag: 'mueble 5'},
    {id: '54', imagenName: 'mueble5_1.png', tag: 'mueble 5'},
    {id: '55', imagenName: 'mueble5_2.png', tag: 'mueble 5'},
    {id: '56', imagenName: 'mueble5_3.jpg', tag: 'mueble 5'},
    {id: '57', imagenName: 'mueble5_4.jpg', tag: 'mueble 5'},

    {id: '58', imagenName: 'mueble6_1.gif', tag: 'mueble 6'},
    {id: '59', imagenName: 'mueble6_1.png', tag: 'mueble 6'},
    {id: '60', imagenName: 'mueble6_2.png', tag: 'mueble 6'},
    {id: '61', imagenName: 'mueble6_3.png', tag: 'mueble 6'},
    {id: '62', imagenName: 'mueble6_4.png', tag: 'mueble 6'},
    {id: '63', imagenName: 'mueble6_5.png', tag: 'mueble 6'},
    {id: '64', imagenName: 'mueble6_6.jpg', tag: 'mueble 6'},
    {id: '65', imagenName: 'mueble6_7.jpg', tag: 'mueble 6'},
    {id: '66', imagenName: 'mueble6_8.jpg', tag: 'mueble 6'},


];